# 打包命令 mvn clean package | 默认打包 dev.yml
# 打包命令 mvn clean package -P dev | 打包 dev.yml
# 打包命令 mvn clean package -P test | 打包 test.yml

server:
  port: 8999
  servlet:
    context-path: /

# --- 日志 --- #
logging:
  save:
    enable: false # 日志是否存储到文件中
  config: classpath:logback-spring.xml
  file:
    # 生成日志文件夹名称
    name: logs

# --- spring --- #
spring:
  application:
    name: seed
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #  ---------- hikari ---------- #
    hikari:
      pool-name: KevinHikariPool
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 150
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 20
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      # 不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #连接测试查询
      connection-test-query: SELECT 1

# --- mybatis-plus --- #
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true

# --- jwt --- #
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

# --- redis --- #
redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

# --- security 白名单 --- #
secure:
  ignored:
    urls:
      # --- 放行knife4j 开始 ---
      - /doc.html
      - /webjars/**
      - /img.icons/**
      - /swagger-resources/**
      - /v3/api-docs
      - /favicon.ico
      # --- 放行 knife4j 结束---
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /actuator/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /admin/code/image
      - /role/downloadFailedUsingJson

# --- security 功能 --- #
security:
  # --- 开启security验证 --- #
  open: true
  # --- 验证码 --- #
  captcha:
    # 开启验证码功能
    open: false
    # 图形验证码配置
    image:
      # 图片宽
      width: 100
      # 图片高
      height: 50
      # 验证码字数
      length: 4
      # 干扰线条数
      lineCount: 2
      # 验证码过期时间 60秒
      expired: 60

# --- forest --- #
forest:
  bean-id: config0 # 在spring上下文中bean的id（默认为 forestConfiguration）
  backend: okhttp3 # 后端HTTP框架（默认为 okhttp3）
  max-connections: 1000 # 连接池最大连接数（默认为 500）
  max-route-connections: 500 # 每个路由的最大连接数（默认为 500）
  timeout: 3000 # 请求超时时间，单位为毫秒（默认为 3000）
  connect-timeout: 3000 # 连接超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 3000 # 数据读取超时时间，单位为毫秒（默认为 timeout）
  max-retry-count: 0 # 请求失败后重试次数（默认为 0 次不重试）
  ssl-protocol: SSLv3 # 单向验证的HTTPS的默认SSL协议（默认为 SSLv3）
  logEnabled: true # 打开或关闭日志（默认为 true）
  log-request: true # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true # 打开/关闭Forest响应内容日志（默认为 false）
  variables:
    xUrl: http://127.0.0.1/xxx # 变量

# --- knife4j --- #
knife4j:
  enable: true
  cors: false
  production: false
  basic:
    enable: true
    username: test
    password: 123
  title: 单体应用接口文档
  description: api描述
  version: 1.0.0
  author: bugProvider
  apiBasePackage: com.bugprovider.seed.modules
springfox:
  documentation:
    open-api:
      enabled: true




