POST http://localhost:8999/admin/login
Content-Type: application/json

{
  "username": "ceshi",
  "password": "123456"
}

###
GET http://localhost:8999/admin/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjZXNoaSIsImNyZWF0ZWQiOjE2Mzc0ODYyNTQyNzcsImV4cCI6MTYzODA5MTA1NH0.HGXvkp1oKvwWA5JrdczqLrH6FFDnmkLbcK95qYAzjWslTPckma8msOH4Ft12LlShRprIwUaR9qglgFB10naNbw
Content-Type: application/json

###
GET http://localhost:8999/subject/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjZXNoaSIsImNyZWF0ZWQiOjE2Mzc0ODYyNTQyNzcsImV4cCI6MTYzODA5MTA1NH0.HGXvkp1oKvwWA5JrdczqLrH6FFDnmkLbcK95qYAzjWslTPckma8msOH4Ft12LlShRprIwUaR9qglgFB10naNbw
Content-Type: application/json

###